feat: validate the PSR summary action

diff --git a/.github/actions/psr-summary/action.yml b/.github/actions/psr-summary/action.yml
--- a/.github/actions/psr-summary/action.yml
+++ b/.github/actions/psr-summary/action.yml
@@ -27,19 +27,20 @@ runs:
         echo "Input validation completed."
         echo ""
 
-        echo "Current directory: $(pwd)"
-        echo "Listing files in current directory:"
-        ls -la
-        echo ""
-
-    - id: generate-summary
+    - id: create-summary-file
       shell: bash
       run: |
+        echo "Current directory: $(pwd)"
+        mkdir -p ./github/log
+        echo ""
         PSR_SUMMARY_FILE_PATH="./github/log/psr_summary.md"
         touch "$PSR_SUMMARY_FILE_PATH"
         echo "psr-summary-file-path=$PSR_SUMMARY_FILE_PATH" >> "$GITHUB_OUTPUT"
 
-
+    - id: generate-summary
+      shell: bash
+      run: |
+        
         {
           echo "## Python Semantic Release - GitHub Action"
           echo ""
@@ -62,6 +63,18 @@ runs:
             echo "Changelog file not found or not provided."
           fi
         } > "$PSR_SUMMARY_FILE_PATH"
+
+    - id: validate-summary
+      shell: bash
+      run: |
+        echo "Validating the generated summary file..."
+        if [ -f "$PSR_SUMMARY_FILE_PATH" ]; then
+          echo "Summary file created successfully at: $PSR_SUMMARY_FILE_PATH"
+          head -n 10 "$PSR_SUMMARY_FILE_PATH"
+        else
+          echo "Error: Summary file was not created."
+          exit 1
+        fi
 
 
 outputs:
