fix: init a changelog if it doesn't exist

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -55,7 +55,7 @@ concurrency:
 jobs:
 
   continuous-delivery:
-    runs-on: ubuntu-latest
+    runs-on: ${{ inputs.action-runs-on }}
     steps:
       - name: Checkout Repository at workflow SHA
         uses: actions/checkout@v5
@@ -65,6 +65,18 @@ jobs:
 
       - name: Force correct release branch on workflow SHA
         run: git checkout -B ${{ inputs.ref }}
+
+      - name: Get the latest CHANGELOG from the `log` branch or initialize it
+        run: |
+          if git ls-remote --exit-code --heads origin log; then
+            echo "log branch found — fetching CHANGELOG.md"
+            git fetch origin log
+            git checkout origin/log -- CHANGELOG.md
+          else
+            echo "log branch not found — creating empty CHANGELOG.md"
+            touch CHANGELOG.md
+            git add -A CHANGELOG.md || true
+          fi
 
       - name: Python Semantic Release
         id: semver
diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -54,7 +54,7 @@ concurrency:
 
 jobs:
   continuous-integration:
-    runs-on: ubuntu-latest
+    runs-on: ${{ inputs.action-runs-on }}
     steps:
       - name: Setup | Checkout Repository at workflow sha
         uses: actions/checkout@v5
@@ -64,6 +64,18 @@ jobs:
 
       - name: Setup | Force correct release branch on workflow SHA
         run: git checkout -B ${{ inputs.ref }}
+
+      - name: Get the latest CHANGELOG from the `log` branch or initialize it
+        run: |
+          if git ls-remote --exit-code --heads origin log; then
+            echo "log branch found — fetching CHANGELOG.md"
+            git fetch origin log
+            git checkout origin/log -- CHANGELOG.md
+          else
+            echo "log branch not found — creating empty CHANGELOG.md"
+            touch CHANGELOG.md
+            git add -A CHANGELOG.md || true
+          fi
 
       - name: Python Semantic Release
         id: psr-ci
