fix: split updating the main branch into a separate job, since the docker container does not have access to the repo url

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -105,17 +105,6 @@ jobs:
           push: ${{ inputs.push }}
           root_options: "-v"
 
-      - name: Update main branch
-        run: |
-          BRANCH=$(git rev-parse --abbrev-ref HEAD)
-          if [ "$BRANCH" != "release" ]; then
-            echo "Not on release branch, skipping merge to main."
-            exit 0
-          fi
-          git checkout main
-          git merge release -m 'ci: merge release into main' || { echo "Merge failed, possibly due to conflicts. Please resolve manually."; exit 1; }
-          git push origin main
-
       - name: Workflow Status
         run: |
           echo "## Python Semantic Release - GitHub Action" >> $GITHUB_STEP_SUMMARY
@@ -125,3 +114,34 @@ jobs:
           echo "Released: ${{ steps.semver.outputs.released }}" >> $GITHUB_STEP_SUMMARY
           echo ""  >> $GITHUB_STEP_SUMMARY
           cat CHANGELOG.md >> $GITHUB_STEP_SUMMARY
+
+  update-main:
+    runs-on: ${{ inputs.action-runs-on }}
+    needs: continuous-delivery
+    steps:
+      - name: Checkout Repository at workflow SHA
+        uses: actions/checkout@v5
+        with:
+          fetch-depth: 1
+          ref: ${{ inputs.ref }}
+
+      - name: Force correct release branch on workflow SHA
+        run: git checkout -B ${{ inputs.ref }}
+
+      - name: Set up SSH agent
+        uses: webfactory/ssh-agent@v0.9.0
+        with:
+          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
+
+      - name: Update main branch
+        run: |
+          BRANCH=$(git rev-parse --abbrev-ref HEAD)
+          if [ "$BRANCH" != "release" ]; then
+            echo "Not on release branch, skipping merge to main."
+            exit 0
+          fi
+          git checkout main
+          git merge release -v -m 'ci: merge release into main' || { echo "Merge failed, possibly due to conflicts. Please resolve manually."; exit 1; }
+          git push origin main
+          
+          echo "Updated Main Branch" >> $GITHUB_STEP_SUMMARY
